# Generated by Django 5.2.7 on 2025-10-30 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название организации')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Outage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outage_type', models.CharField(choices=[('WATER', 'Водоснабжение'), ('ELECTRICITY', 'Электричество'), ('GAS', 'Газ'), ('HEATING', 'Отопление')], max_length=20, verbose_name='Тип отключения')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('buildings', models.ManyToManyField(to='outages.building', verbose_name='Здания')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outages.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Отключение',
                'verbose_name_plural': 'Отключения',
                'ordering': ['-start_time'],
            },
        ),
    ]
